# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "379f5f3b7986eff9a223a41545b75f9e"
web_directories = [ "frontend" ]
name = "ai-intelligent-site"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/api/v1/shopify/webhooks/ingress/00000000-0000-0000-0000-000000000001"
  topics = [
  "app/uninstalled",
  "products/create",
  "products/delete",
  "products/update"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/v1/shopify/oauth/callback" ]
