#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

TENANT_ID="00000000-0000-0000-0000-000000000001"
STORE_DOMAIN="ai-intelligent-site-test.myshopify.com"
INGRESS_URL="http://localhost:8000/api/v1/shopify/webhooks/ingress/$TENANT_ID"

# Git Bash may not expose explorer.exe/xdg-open reliably. Prefer the native
# Windows browser launcher when PowerShell is available.
if command -v powershell.exe >/dev/null 2>&1; then
  open_url() {
    local url="$1"
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
    powershell.exe -NoProfile -Command "Start-Process -FilePath '$url'" \
      >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
  }
fi

if [[ ! -f compose.yaml ]]; then
  printf 'Run this wizard from the repository root (compose.yaml was not found).\n' >&2
  exit 1
fi

psql_query() {
  docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U postgres -d ai_site -P pager=off -c "$1"
}

banner "Shopify live validation"

stage "Environment and connected UI"
say "Keep shopify app dev running in a separate terminal for every browser step."
step "Review the backend, worker, database, and Redis container status."
docker compose ps backend worker postgres redis
if ! docker compose ps --status running backend worker postgres redis | grep -q "backend"; then
  warn "required Compose services are not all running"
  exit 1
fi
REDIRECT_URI=$(docker compose exec -T backend python -c "from app.config import get_settings; print(get_settings().shopify_redirect_uri)" | tr -d '\r')
say "Backend OAuth redirect URI: $REDIRECT_URI"
if [[ "$REDIRECT_URI" != https://*.trycloudflare.com/api/v1/shopify/oauth/callback ]]; then
  warn "redirect URI is not the current trycloudflare callback; update .env and recreate backend + worker"
  exit 1
fi
open_url "http://localhost:3000"
step "Log in, open 店铺连接, and confirm $STORE_DOMAIN shows 已连接."
confirm "Does the UI show the store as 已连接?" || { warn "stop here and fix the connection status"; exit 1; }

stage "Tenant, scope, and encrypted token"
say "This query exposes only tenant, status, scopes, ciphertext length, and nonce presence."
psql_query "SELECT tenant_id, shop_domain, status, granted_scopes, octet_length(encrypted_access_token) AS ciphertext_bytes, (access_token_nonce IS NOT NULL) AS has_nonce FROM shopify_stores WHERE shop_domain = '$STORE_DOMAIN';"
DB_CHECK=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT (tenant_id = '$TENANT_ID'::uuid AND status = 'connected' AND granted_scopes::jsonb @> '[\"write_content\",\"write_products\"]'::jsonb AND jsonb_array_length(granted_scopes::jsonb) = 2 AND octet_length(encrypted_access_token) > 0 AND access_token_nonce IS NOT NULL) FROM shopify_stores WHERE shop_domain = '$STORE_DOMAIN';" | tr -d '\r')
if [[ "$DB_CHECK" != "t" ]]; then
  warn "tenant, scope, connection, or ciphertext validation failed"
  exit 1
fi
TOKEN_COLUMNS=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT string_agg(column_name, ',') FROM information_schema.columns WHERE table_name = 'shopify_stores' AND column_name ILIKE '%access_token%';" | tr -d '\r')
say "Token-related database columns: $TOKEN_COLUMNS"
EXPECTED_TOKEN_COLUMNS="access_token_nonce,encrypted_access_token"

SORTED_TOKEN_COLUMNS=$(echo "$TOKEN_COLUMNS" | tr ',' '\n' | sort | paste -sd ',' -)

if [[ "$SORTED_TOKEN_COLUMNS" != "$EXPECTED_TOKEN_COLUMNS" ]]; then
  warn "unexpected token-related column detected: $TOKEN_COLUMNS"
  exit 1
fi
if docker compose logs backend worker 2>/dev/null | grep -Eq 'shpat_|shpua_'; then
  warn "a Shopify-token-like value appears in application logs; inspect securely before continuing"
  exit 1
fi
say "✓ tenant, least scopes, ciphertext storage, nonce, and token-log scan passed"
pause "Press Enter to continue."

stage "Real Shopify products/update webhook"
open_url "https://admin.shopify.com/store/ai-intelligent-site-test/products"
step "Open any product (create one first if needed), make a harmless title/description edit, and click Save."
pause "Press Enter only after Shopify confirms the product was saved."
say "Latest Shopify webhook events:"
psql_query "SELECT webhook_id, topic, status, received_at, processed_at FROM shopify_webhook_events ORDER BY received_at DESC LIMIT 5;"
REAL_WEBHOOK=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT (topic = 'products/update' AND status = 'processed') FROM shopify_webhook_events ORDER BY received_at DESC LIMIT 1;" | tr -d '\r')
if [[ "$REAL_WEBHOOK" != "t" ]]; then
  warn "latest event is not a processed products/update webhook"
  say "Wait a few seconds, confirm webhook subscriptions were deployed, then re-run this stage."
  exit 1
fi
say "✓ a real Shopify products/update event reached the app and was processed"
pause "Press Enter to continue."

stage "HMAC rejection and duplicate idempotency"
say "First send a local request with an intentionally invalid HMAC."
INVALID_BODY_FILE=$(mktemp)
INVALID_STATUS=$(curl -sS -o "$INVALID_BODY_FILE" -w '%{http_code}' -X POST "$INGRESS_URL" \
  -H 'Content-Type: application/json' \
  -H 'X-Shopify-Hmac-Sha256: deliberately-invalid' \
  -H 'X-Shopify-Webhook-Id: wizard-invalid-hmac' \
  -H "X-Shopify-Shop-Domain: $STORE_DOMAIN" \
  -H 'X-Shopify-Topic: products/update' \
  -H 'X-Shopify-API-Version: 2026-07' \
  --data '{"id":1,"title":"must be rejected"}')
rm -f "$INVALID_BODY_FILE"
if [[ "$INVALID_STATUS" != "401" ]]; then
  warn "invalid HMAC returned HTTP $INVALID_STATUS instead of 401"
  exit 1
fi
say "✓ invalid HMAC returned 401"
say "Now send the same correctly signed webhook ID twice without printing the secret."
docker compose exec -T backend python - <<'PY'
import base64
import hashlib
import hmac
import json
import urllib.error
import urllib.request
import uuid

from app.config import get_settings

tenant_id = "00000000-0000-0000-0000-000000000001"
shop = "ai-intelligent-site-test.myshopify.com"
body = json.dumps({"id": 424242, "title": "wizard idempotency probe"}).encode()
webhook_id = f"wizard-{uuid.uuid4().hex}"
secret = get_settings().shopify_client_secret.get_secret_value().encode()
signature = base64.b64encode(hmac.new(secret, body, hashlib.sha256).digest()).decode()
headers = {
    "Content-Type": "application/json",
    "X-Shopify-Hmac-Sha256": signature,
    "X-Shopify-Webhook-Id": webhook_id,
    "X-Shopify-Shop-Domain": shop,
    "X-Shopify-Topic": "products/update",
    "X-Shopify-API-Version": "2026-07",
}
url = f"http://localhost:8000/api/v1/shopify/webhooks/ingress/{tenant_id}"

def post():
    request = urllib.request.Request(url, data=body, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(request) as response:
            return response.status, json.loads(response.read())
    except urllib.error.HTTPError as error:
        return error.code, json.loads(error.read())

first = post()
second = post()
print(f"first_status={first[0]} first_result={first[1].get('status')}")
print(f"second_status={second[0]} second_result={second[1].get('status')}")
if first[0] != 202 or first[1].get("status") != "accepted":
    raise SystemExit("first signed webhook was not accepted")
if second[0] != 200 or second[1].get("status") != "duplicate":
    raise SystemExit("duplicate webhook was not deduplicated")
PY
say "✓ valid HMAC was accepted and the duplicate returned 200 duplicate"
pause "Press Enter to continue."

stage "SEO baseline on a real product"
say "Choose one local product that has already been published to the Development Store."
psql_query "SELECT id, title, status, shopify_product_id FROM products WHERE shopify_product_id IS NOT NULL ORDER BY updated_at DESC LIMIT 10;"
PUBLISHED_PRODUCT_COUNT=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT count(*) FROM products WHERE shopify_product_id IS NOT NULL;" | tr -d '\r')
if [[ "$PUBLISHED_PRODUCT_COUNT" == "0" ]]; then
  warn "No local product is mapped to a real Shopify product yet."
  open_url "http://localhost:3000"
  step "Open 审核队列, select one demo product draft, then choose 通过 → 发布 → 确认发布."
  pause "Press Enter after the UI reports that Shopify confirmed the publish."
  psql_query "SELECT id, title, status, shopify_product_id FROM products WHERE shopify_product_id IS NOT NULL ORDER BY updated_at DESC LIMIT 10;"
  PUBLISHED_PRODUCT_COUNT=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT count(*) FROM products WHERE shopify_product_id IS NOT NULL;" | tr -d '\r')
  if [[ "$PUBLISHED_PRODUCT_COUNT" == "0" ]]; then
    warn "No Shopify product mapping was created; stop and resolve the publish failure before validation."
    exit 1
  fi
fi
open_url "http://localhost:3000"
step "Open 商品, choose that published product, and open its version history."
open_url "https://admin.shopify.com/store/ai-intelligent-site-test/products"
step "Open the matching Shopify product and record Title, website SEO title/description, tags, and the first image Alt text."
confirm "Do the local product and Shopify product refer to the same item?" || { warn "product mapping must be correct before SEO validation"; exit 1; }
pause "Keep both product pages open, then press Enter."

stage "Low-risk SEO auto-write"
open_url "http://localhost:3000"
step "On the published product, click SEO 优化 (not SEO 标题优化)."
step "Open 审核队列 and wait until the SEO item shows 已写入 Shopify."
open_url "https://admin.shopify.com/store/ai-intelligent-site-test/products"
step "Refresh the matching Shopify product. Verify website SEO title/description, tags, and image Alt changed to the generated suggestion."
confirm "Did low-risk SEO write automatically to Shopify?" || { warn "low-risk remote write validation failed"; exit 1; }
step "Back in the local product version history, identify the new publish snapshot. Its payload is the pre-SEO baseline used later for rollback."
pause "Record that snapshot version, then press Enter."

stage "Title waits for human review"
open_url "http://localhost:3000"
step "On the same product, click SEO 标题优化."
step "Open 审核队列 and wait until the item shows 等待审核. Do not approve it yet."
open_url "https://admin.shopify.com/store/ai-intelligent-site-test/products"
step "Refresh the matching Shopify product and verify its Title has not changed."
confirm "Is the remote Title unchanged before approval?" || { warn "medium-risk review gate validation failed"; exit 1; }
step "Return to 审核队列, approve the title draft, click 发布, and confirm the high-risk prompt."
step "Refresh Shopify and verify the approved Title is now present."
confirm "Did Shopify change only after approval and explicit publish?" || { warn "reviewed title publish validation failed"; exit 1; }

stage "SEO snapshot rollback"
open_url "http://localhost:3000"
step "Open the same product's version history."
step "Rollback to the publish snapshot recorded before the low-risk SEO write, and confirm the rollback prompt."
open_url "https://admin.shopify.com/store/ai-intelligent-site-test/products"
step "Refresh the matching Shopify product and verify Title, website SEO fields, tags, and image Alt match the recorded baseline."
confirm "Did a fresh Shopify read confirm the baseline was restored?" || { warn "remote rollback validation failed"; exit 1; }
say "✓ Issue #17 Shopify validation passed: remote baseline, risk gate, write, and rollback were observed."
pause "Record evidence in issue #17, then press Enter."

stage "Uninstall and disconnected state"
warn "This stage uninstalls the app from the development store and revokes its token."
open_url "https://admin.shopify.com/store/ai-intelligent-site-test/settings/apps"
step "Open Apps and sales channels, choose ai-intelligent-site, then click Uninstall."
confirm "Are you ready to uninstall from the development store?" || { warn "uninstall skipped"; exit 1; }
pause "Press Enter after Shopify confirms the app was uninstalled."
say "Waiting briefly for app/uninstalled to be processed..."
for _ in 1 2 3 4 5 6 7 8 9 10; do
  DISCONNECTED=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT (status = 'disconnected' AND encrypted_access_token IS NULL AND access_token_nonce IS NULL AND disconnected_at IS NOT NULL) FROM shopify_stores WHERE shop_domain = '$STORE_DOMAIN';" | tr -d '\r')
  [[ "$DISCONNECTED" == "t" ]] && break
  sleep 2
done
psql_query "SELECT shop_domain, status, (encrypted_access_token IS NULL) AS token_cleared, (access_token_nonce IS NULL) AS nonce_cleared, disconnected_at FROM shopify_stores WHERE shop_domain = '$STORE_DOMAIN';"
if [[ "$DISCONNECTED" != "t" ]]; then
  warn "uninstall did not produce a disconnected row with cleared token material"
  exit 1
fi
open_url "http://localhost:3000"
step "Open 店铺连接 and confirm the UI now displays 已断开."
confirm "Does the UI show 已断开?" || { warn "frontend disconnect state validation failed"; exit 1; }

stage "Reinstall and final recovery"
open_url "http://localhost:3000"
step "On 店铺连接, enter $STORE_DOMAIN and click 连接 Shopify 店铺."
step "Approve the Shopify installation again, then wait up to three seconds for polling."
pause "Press Enter after the UI reports 已连接 again."
RECONNECTED=$(docker compose exec -T postgres psql -U postgres -d ai_site -At -c "SELECT (status = 'connected' AND encrypted_access_token IS NOT NULL AND access_token_nonce IS NOT NULL AND granted_scopes::jsonb @> '[\"write_content\",\"write_products\"]'::jsonb AND jsonb_array_length(granted_scopes::jsonb) = 2) FROM shopify_stores WHERE shop_domain = '$STORE_DOMAIN';" | tr -d '\r')
psql_query "SELECT tenant_id, shop_domain, status, granted_scopes, octet_length(encrypted_access_token) AS ciphertext_bytes, connected_at, disconnected_at FROM shopify_stores WHERE shop_domain = '$STORE_DOMAIN';"
if [[ "$RECONNECTED" != "t" ]]; then
  warn "reinstall did not restore the connected encrypted-token state"
  exit 1
fi
say "✓ reinstall restored the connected state with least scopes and encrypted token"
say "Record the results in docs/shopify-live-validation.md and issue #13."
pause "Press Enter to finish."

finish
